CREATE TABLE SFM.APP_SEQUENCE (
  SEQ_NAME VARCHAR(20) PRIMARY KEY,
  SEQ_VALUE BIGINT CHECK (SEQ_VALUE > 0) NOT NULL
);

CREATE TABLE SFM.ACCESS_TOKEN (
  ACCESS_ID BIGINT PRIMARY KEY,
  INSERT_DATE TIMESTAMP(0) NOT NULL,
  USER_NAME VARCHAR(30) NOT NULL,
  EXPIRY_DATE TIMESTAMP(0) NOT NULL,
  REFRESH_COUNT INT NOT NULL,
  LAST_REFRESH_DATE TIMESTAMP(0)
);

CREATE TABLE SFM.COUNTRY_MASTER(
	COUNTRY_ID INT PRIMARY KEY,
	COUNTRY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SFM.STATE_MASTER(
	STATE_ID INT PRIMARY KEY,
	STATE_NAME VARCHAR(32) NOT NULL,
	COUNTRY_ID INT NOT NULL,
	FOREIGN KEY(COUNTRY_ID) REFERENCES SFM.COUNTRY_MASTER(COUNTRY_ID)
);

CREATE TABLE SFM.DISTRICT_MASTER(
	DISTRICT_ID INT PRIMARY KEY,
	DISTRICT_NAME VARCHAR(32) NOT NULL,
	STATE_ID INT NOT NULL,
	FOREIGN KEY(STATE_ID) REFERENCES SFM.STATE_MASTER(STATE_ID)
);

CREATE TABLE SFM.ROLE_MASTER (
	ROLE_ID INT PRIMARY KEY,
	ROLE_NAME VARCHAR(30) NOT NULL,
	ROLE_DESCRIPTION VARCHAR(60) NOT NULL
);

CREATE TABLE SFM.PERMISSION_MASTER (
	PERMISSION_ID INT PRIMARY KEY,
	PERMISSION_NAME VARCHAR(50) NOT NULL UNIQUE KEY,
	PERMISSION_TYPE VARCHAR(1) NOT NULL,
	RESOURCE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SFM.ROLE_PERMISSION (
	ROLE_ID INT NOT NULL,
	PERMISSION_ID INT NOT NULL,
	PRIMARY KEY (ROLE_ID, PERMISSION_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES SFM.ROLE_MASTER(ROLE_ID),
	FOREIGN KEY(PERMISSION_ID) REFERENCES SFM.PERMISSION_MASTER(PERMISSION_ID)
);

CREATE TABLE SFM.DIVISION (
	DIV_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	DIV_NAME VARCHAR(100) NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP
);

CREATE TABLE SFM.PRODUCT (
	PROD_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	PROD_NAME VARCHAR(100) NOT NULL,
	VFROM DATE NOT NULL,
	VTO DATE,
	PRICE DECIMAL(32,2) NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP
);

CREATE TABLE SFM.SALES_REP (
	SALES_REP_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	SUP_ID INT,
	STATUS_ID SMALLINT NOT NULL,
	EXTN VARCHAR(10),
	LAND VARCHAR(20),
	MOB VARCHAR(20),
	EMAIL VARCHAR(100) NOT NULL,
	DOJ DATE NOT NULL,
	DESIG VARCHAR(100) NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(SUP_ID) REFERENCES SFM.SALES_REP(SALES_REP_ID),	
	FOREIGN KEY(STATUS_ID) REFERENCES SFM.STATUS(STATUS_ID)
);

CREATE TABLE SFM.SALES_REP_PROFILE (
	SALES_REP_ID INT,
	IMG TEXT
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP	
);

CREATE TABLE SFM.CONTACT (
	CO_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	STATUS_ID SMALLINT NOT NULL,
	FIRST_NAME VARCHAR(60) NOT NULL,
	MIDDLE_NAME VARCHAR(60),
	LAST_NAME VARCHAR(60),
	COMPANY VARCHAR(100),
	DESIGNATION VARCHAR(50),
	EMAIL VARCHAR(100) NOT NULL,
	EXTN VARCHAR(10),
	LAND VARCHAR(20),
	MOB VARCHAR(20),
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,	
	FOREIGN KEY(STATUS_ID) REFERENCES SFM.STATUS(STATUS_ID)
);

CREATE TABLE SFM.CONTACT_ATTR (
	CO_ID INT PRIMARY KEY,
	ADDR_LINE_1 VARCHAR(200),
	ADDR_LINE_2 VARCHAR(200),
	DISTRICT_ID SMALLINT,
	STATE_ID SMALLINT,
	COUNTRY_ID SMALLINT,
	ZIP_CODE VARCHAR(15),
	NOTE VARCHAR(2000),
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(COUNTRY_ID) REFERENCES SFM.COUNTRY_MASTER(COUNTRY_ID),
	FOREIGN KEY(STATE_ID) REFERENCES SFM.STATE_MASTER(STATE_ID),
	FOREIGN KEY(DISTRICT_ID) REFERENCES SFM.DISTRICT_MASTER(DISTRICT_ID),
	FOREIGN KEY(CO_ID) REFERENCES SFM.CONTACT(CO_ID)
);

CREATE TABLE SFM.LEAD (
	LEAD_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	TITLE VARCHAR(100) NOT NULL,
	TOTAL_PROD_QUOTE DECIMAL(32,2),
	DISC_AMT DECIMAL(32,2),
	DISC_PCT DECIMAL(3,2),
	QUOTE_PRICE DECIMAL(32,2),
	STATUS_ID SMALLINT NOT NULL,
	DIV_ID INT NOT NULL,
	ACC_ID INT,
	OPP_ID INT,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(DIV_ID) REFERENCES SFM.DIVISION(DIV_ID),
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),	
	FOREIGN KEY(STATUS_ID) REFERENCES SFM.STATUS(STATUS_ID)
);

CREATE TABLE SFM.LEAD_ATTR (
	LEAD_ID INT PRIMARY KEY,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID)
);

CREATE TABLE SFM.LEAD_PROD (
	LEAD_ID INT,
	PROD_ID INT,
	PROD_UNIT DECIMAL(32,2),
	DISC_AMT DECIMAL(32,2),
	DISC_PCT DECIMAL(3,2),
	QUOTE_UNIT_PRICE DECIMAL(32,2),
	QUOTE_PRICE DECIMAL(32,2),
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID),
	FOREIGN KEY(PROD_ID) REFERENCES SFM.PRODUCT(PROD_ID),
	PRIMARY KEY (LEAD_ID, PROD_ID)
);

CREATE TABLE SFM.LEAD_CONTACT (
	LEAD_ID INT NOT NULL,
	CO_ID INT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID),
	FOREIGN KEY(CO_ID) REFERENCES SFM.LEAD(CO_ID),
	PRIMARY KEY (LEAD_ID, CO_ID)
);

CREATE TABLE SFM.LEAD_TIMELINE (
	ENTRY_ID BIGINT PRIMARY KEY,
	LEAD_ID INT NOT NULL,
	ATT_ID INT,
	NOTE TEXT NOT NULL,
	CRTD_BY VARCHAR(15),
	CRTD_ON TIMESTAMP,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID),
	FOREIGN KEY(ATT_ID) REFERENCES SFM.LEAD_ATTACHMENT(ATT_ID)	
);

CREATE TABLE SFM.LEAD_ATTACHMENT (
	ATT_ID INT PRIMARY KEY,
	LEAD_ID INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	ATT TEXT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID)
);

CREATE TABLE SFM.OPPORTUNITY (
	OPP_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	TOTAL_PROD_QUOTE DECIMAL(32,2),
	DISC_AMT DECIMAL(32,2),
	DISC_PCT DECIMAL(3,2),
	QUOTE_PRICE DECIMAL(32,2),
	SOLD_PRICE DECIMAL(32,2),
	TITLE VARCHAR(100) NOT NULL,
	STATUS_ID SMALLINT NOT NULL,
	DIV_ID INT NOT NULL,
	ACC_ID INT,
	LEAD_ID INT,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(DIV_ID) REFERENCES SFM.DIVISION(DIV_ID),
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID),	
	FOREIGN KEY(STATUS_ID) REFERENCES SFM.STATUS(STATUS_ID)
);

CREATE TABLE SFM.OPPORTUNITY_ATTR (
	OPP_ID INT PRIMARY KEY,
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID)
);

CREATE TABLE SFM.OPPORTUNITY_PROD (
	OPP_ID INT,
	PROD_ID INT,
	PROD_UNIT DECIMAL(32,2),
	DISC_AMT DECIMAL(32,2),
	DISC_PCT DECIMAL(3,2),
	QUOTE_UNIT_PRICE DECIMAL(32,2),	
	QUOTE_PRICE DECIMAL(32,2),
	CRTD_BY VARCHAR(15),
	CRTD_ON TIMESTAMP,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(PROD_ID) REFERENCES SFM.PRODUCT(PROD_ID),
	PRIMARY KEY (OPP_ID, PROD_ID)
);

CREATE TABLE SFM.OPPORTUNITY_CONTACT (
	OPP_ID INT,
	CO_ID INT,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(CO_ID) REFERENCES SFM.CONTACT(CO_ID),
	PRIMARY KEY (OPP_ID, CO_ID)
);

CREATE TABLE SFM.OPPORTUNITY_TIMELINE (
	ENTRY_ID BIGINT PRIMARY KEY,
	LEAD_ID INT,
	OPP_ID INT NOT NULL,
	ATT_ID INT,
	NOTE TEXT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(ATT_ID) REFERENCES SFM.OPPORTUNITY_ATTACHMENT(ATT_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID),
);

CREATE TABLE SFM.OPPORTUNITY_ATTACHMENT (
	ATT_ID INT PRIMARY KEY,
	LEAD_ID INT NOT NULL,
	OPP_ID INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	ATT TEXT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID)
);

CREATE TABLE SFM.ACCOUNT (
	ACC_ID INT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	TITLE  VARCHAR(100) NOT NULL,
	STATUS_ID SMALLINT NOT NULL,
	DIV_ID INT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(DIV_ID) REFERENCES SFM.DIVISION(DIV_ID),	
	FOREIGN KEY(STATUS_ID) REFERENCES SFM.STATUS(STATUS_ID)
);

CREATE TABLE SFM.ACCOUNT_ATTR (
	ACC_ID INT PRIMARY KEY,
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID)
);

CREATE TABLE SFM.ACCOUNT_PROD (
	ACC_ID INT NOT NULL,
	OPP_ID INT NOT NULL,
	LEAD_ID INT NOT NULL,
	PROD_ID INT NOT NULL,
	DISC_AMT DECIMAL(32,2),
	DISC_PCT DECIMAL(3,2),
	QUOTE_PRICE DECIMAL(32,2) NOT NULL,
	SOLD_PRICE DECIMAL(32,2) NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	PRIMARY KEY (ACC_ID, OPP_ID, LEAD_ID),
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(OPP_ID) REFERENCES SFM.ACCOUNT(OPP_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.ACCOUNT(LEAD_ID)	
);

CREATE TABLE SFM.ACCOUNT_CONTACT (
	ACC_ID INT NOT NULL,
	CO_ID INT NOT NULL,
	LEAD_ID INT NOT NULL,
	OPP_ID INT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	PRIMARY KEY (ACC_ID, CO_ID, OPP_ID, LEAD_ID),
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(OPP_ID) REFERENCES SFM.ACCOUNT(OPP_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.ACCOUNT(LEAD_ID),
	FOREIGN KEY(CO_ID) REFERENCES SFM.ACCOUNT(CO_ID)
);

CREATE TABLE ACCOUNT_TIMELINE (
	ENTRY_ID BIGINT PRIMARY KEY,
	ACC_ID INT NOT NULL,
	OPP_ID INT,
	LEAD_ID INT,
	ATT_ID INT,
	NOTE TEXT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID)
);

CREATE TABLE ACCOUNT_ATTACHMENT (
	ATT_ID INT PRIMARY KEY,
	ACC_ID INT NOT NULL,
	OPP_ID INT,
	LEAD_ID INT,
	TITLE VARCHAR(100) NOT NULL,
	ATT TEXT NOT NULL,
	CRTD_BY VARCHAR(15) NOT NULL,
	CRTD_ON TIMESTAMP NOT NULL,
	MOD_BY VARCHAR(15),
	MOD_ON TIMESTAMP,
	FOREIGN KEY(ACC_ID) REFERENCES SFM.ACCOUNT(ACC_ID),
	FOREIGN KEY(OPP_ID) REFERENCES SFM.OPPORTUNITY(OPP_ID),
	FOREIGN KEY(LEAD_ID) REFERENCES SFM.LEAD(LEAD_ID)	
);

CREATE TABLE STATUS (
	STATUS_ID SMALLINT PRIMARY KEY,
	PUB_KEY VARCHAR(15) NOT NULL UNIQUE KEY,
	DES VARCHAR(20) NOT NULL,
	COLOR VARCHAR(10),
	ENTITY VARCHAR(15),
	SORT_ORDER SMALLINT
);